# Fallback generator (Python) — mirrors gen-characters.mjs output exactly.
# Use when Node is unavailable. Run from frontend/: python scripts/gen_characters.py
import os, re, json
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))
FRONTEND = os.path.dirname(HERE)
ROOT = os.path.join(FRONTEND, 'public', 'characters', 'pipoya')
OUT = os.path.join(FRONTEND, 'lib', 'characters.generated.ts')

CATEGORY = {
    'Male': ('m', '남성', 1), 'Female': ('f', '여성', 2), 'Soldier': ('s', '군인', 3),
    'Japanese school characters/school uniform 1': ('su1', '교복 1', 4),
    'Japanese school characters/school uniform 2': ('su2', '교복 2', 5),
    'Japanese school characters/school uniform 3': ('su3', '교복 3', 6),
    'Japanese school characters/school uniform 4': ('su4', '교복 4', 7),
    'Japanese school characters/teachers': ('tch', '교사', 8),
    '__NEKONIN__': ('nk', '고양이닌자', 9),
    'Animal': ('a', '동물', 10), 'Xmas': ('x', '크리스마스', 11),
    'Enemy': ('e', '몬스터', 12), 'Boss': ('b', '보스', 13), 'Other': ('o', '기타', 14),
}


def slug(s):
    return re.sub(r'^-+|-+$', '', re.sub(r'[^a-z0-9]+', '-', s.lower()))


def file_tail(base, code):
    s = re.sub(r'^pipo-charachip[_-]?', '', base, flags=re.I)
    s = re.sub(r'^pipo-xmaschara', '', s, flags=re.I)
    s = re.sub(r'^pipo-nekonin', '', s, flags=re.I)
    s = re.sub(r'^pipo-', '', s, flags=re.I)
    t = slug(s)
    redundant = {'m': 'male', 'f': 'female', 's': 'soldier', 'e': 'enemy', 'b': 'boss'}
    w = redundant.get(code)
    if w and t.startswith(w + '-'):
        t = t[len(w) + 1:]
    return t or '01'


files = []
for dp, _, fns in os.walk(ROOT):
    for fn in fns:
        if fn.lower().endswith('.png'):
            files.append(os.path.join(dp, fn))

entries = []
seen = set()
warn = []
for abs_ in files:
    rel = os.path.relpath(abs_, ROOT).replace(os.sep, '/')
    segs = rel.split('/')
    pack = segs[0]
    is_nk = 'NEKONIN' in pack.upper()
    inner = '/'.join(segs[1:-1])
    key = '__NEKONIN__' if is_nk else inner
    cat = CATEGORY.get(key)
    if not cat:
        warn.append(rel)
        continue
    code, ko, order = cat
    base = re.sub(r'\.png$', '', segs[-1], flags=re.I)
    tail = file_tail(base, code)
    id_ = code + '-' + tail
    n = 2
    while id_ in seen:
        id_ = code + '-' + tail + '-' + str(n)
        n += 1
    seen.add(id_)
    src = '/characters/pipoya/' + rel
    entries.append((id_, ko + ' ' + tail, ko, order, src))

entries.sort(key=lambda e: (e[3], e[0]))
toolong = [e[0] for e in entries if len(e[0]) > 40]
assert not toolong, toolong

lines = []
for id_, label, ko, order, src in entries:
    lines.append('  { id: %s, label: %s, category: %s, src: %s },' % (
        json.dumps(id_, ensure_ascii=False), json.dumps(label, ensure_ascii=False),
        json.dumps(ko, ensure_ascii=False), json.dumps(src, ensure_ascii=False)))
body = '\n'.join(lines)

out = (
    '// AUTO-GENERATED by scripts/gen-characters.mjs — do not edit by hand.\n'
    '// %d Pipoya sprites. Each sheet is a 3-col x 4-row walk grid;\n'
    '// the avatar renders the front-idle frame (col 1, row 0).\n\n'
    'export interface CharacterDef {\n'
    '  id: string;\n'
    '  label: string;\n'
    '  category: string;\n'
    '  src: string;\n'
    '}\n\n'
    '/** Frames per sheet: 3 walk columns, 4 direction rows. Front-idle = (col 1, row 0). */\n'
    'export const SHEET_COLS = 3;\n'
    'export const SHEET_ROWS = 4;\n'
    'export const IDLE_COL = 1;\n'
    'export const IDLE_ROW = 0;\n\n'
    'export const CHARACTERS: CharacterDef[] = [\n'
    '%s\n'
    '];\n'
) % (len(entries), body)

open(OUT, 'w', encoding='utf-8').write(out)
print('wrote', len(entries), 'characters ->', OUT)
if warn:
    print('WARN uncategorized:', warn)
print('by category:', dict(Counter(e[2] for e in entries)))
